### ISSUE TITLE
Support old platform versions?

### ISSUE THREAD

**Issue by AnthonyMastrean** [johnlawerance/crucible#13]
I have the unfortunate responsibility to support an end-of-life instance of Crucible 2.4.4. It has some pretty restrictive [supported platforms](https://confluence.atlassian.com/display/CRUCIBLE024/Supported+Platforms#SupportedPlatforms-1). The first thing I'm trying to do is get this version under Puppet control, then upgrade/migrate/etc.

Do you have any intention of supporting end-user specified platform versions?

```
class { '::crucible':
  version => '2.4.4',
  java_version => '6',
}
```

Or, encoding this (it's fixed in time) in the internal parameters?

**Comment by johnlawerance** [comment]
Thanks for opening @AnthonyMastrean -- Is the question you're asking if we can add in support to specify an older version of java?

**Comment by AnthonyMastrean** [comment]
Not necessarily, if your intention is to provide the latest/best Crucible (and I checked, the latest works fine with whatever is downloaded by default). I'm going to try something like this...

```
    class { '::crucible':
        version      => '2.4.4',
        install_java => false,
    }

    java::oracle { 'jdk6' :
        ensure  => 'present',
        version => '6',
        java_se => 'jre',
    }
```

**Comment by johnlawerance** [comment]
Gotcha thanks @AnthonyMastrean that makes sense. -- I'll close this out, feel free to open other feature requests if you run in to anything else!
