### ISSUE TITLE
Add Ubuntu Support

### ISSUE THREAD

**Issue by AlexanderNZ** [johnlawerance/crucible#4]
Hi John,

I'd like to modify this module so it's compatible with Ubuntu, and submit that work as a pull request, just wanted to check that you're open to that?

Cheers

Alex

**Comment by johnlawerance** [comment]
Yeah absolutely. Feel free to submit the work as a PR. If you'd like to collaborate on it as well hit me up.

**Comment by AlexanderNZ** [comment]
You know what, I've just got around to testing it, and it looks like this module already works perfectly with Ubuntu - I can't see anything in the module code itself that would break ubuntu so..yeah. Guess we can close this issue.

**Comment by johnlawerance** [comment]
@AlexanderNZ Thanks for the info. I haven't done any Ubuntu testing on this module yet. Can you let me know which version of Ubuntu you're using?

**Comment by AlexanderNZ** [comment]
No worries @johnlawerance :)

lsbdistdescription is	Ubuntu 14.04.4 LTS. Kernel is 4.2

Any other details you'd like?

**Comment by johnlawerance** [comment]
Reopening. Tested on Ubuntu 14.04 and see some issues. Assigning to self.
